version: "3.7"

services:
  # PHP-FPM
  php:
    container_name: ${APP_NAME}_php
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.override.ini:ro
      - ./docker/logs/php-fpm:/var/log/php-fpm
    expose:
      - "9000"
    depends_on:
      - redis

  # Nginx
  nginx:
    container_name: ${APP_NAME}_nginx
    restart: always
    build:
      context: docker/nginx
    deploy:
      resources:
        limits:
          memory: 192M
          cpus: '2.0'
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - php
    links:
      - php
    ports:
      [88:80]

  # Redis
  redis:
    container_name: ${APP_NAME}_redis
    image: "redis:alpine"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 20M

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

    healthcheck:
      test: "/usr/local/bin/redis-cli ping"
      interval: 2s
      timeout: 20s
      retries: 10

    sysctls:
      net.core.somaxconn: '511'
